services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config      # ← volume config
    command: mosquitto -c /mosquitto/config/mosquitto.conf

  timescaledb:
    image: timescale/timescaledb:latest-pg16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: devpass
    volumes:
      - pgdata:/var/lib/postgresql/data           # ← volume données

  receiver:
    build: .
    command: python src/iot/mqtt/receiver_mqtt.py
    env_file: .env
    depends_on: [mosquitto, timescaledb]
    restart: unless-stopped

  api:
    build: .
    command: uvicorn iot.api.main:app --host 0.0.0.0 --port 8000
    env_file: .env
    ports:
      - "8000:8000"
    depends_on: [timescaledb]
    restart: unless-stopped

  surveillance:
    build: .
    command: python src/iot/alertes/suveillance.py
    env_file: .env
    depends_on: [timescaledb]
    restart: unless-stopped

volumes:
  pgdata: